/* Copyright Statement:
 *
 * (C) 2024  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __HAL_CCNI_CONFIG_H__
#define __HAL_CCNI_CONFIG_H__

#ifdef HAL_CCNI_MODULE_ENABLED

#include "hal_ccni.h"
#include "memory_attribute.h"

#ifdef __cplusplus
extern "C" {
#endif

#define    HAL_CCNI_EVENT(num)               num
#define    HAL_CCNI_EVENT_MIN                HAL_CCNI_EVENT(0)
#define    HAL_CCNI_SUPPORT_MSG_MAX          HAL_CCNI_EVENT(16)

#define    CCNI_DEF_HANDLER(event_num)       hal_ccni_event_callback##event_num

typedef enum {
    HAL_CCNI_CORE_START = 0x1,
    HAL_CCNI_CORE_MCU = 0x1,
    HAL_CCNI_CORE_RISCV = 0x2,
    HAL_CCNI_CORE_END = 0x3,
    HAL_CCNI_CORE_RESERVED = 0xFFFFFFFF,
} hal_ccni_core_t;

typedef enum {
    HAL_CCNI_EVENT0 = 0,
    HAL_CCNI_EVENT1,
    HAL_CCNI_EVENT2,
    HAL_CCNI_EVENT3,
    HAL_CCNI_EVENT4,
    HAL_CCNI_EVENT5,
    HAL_CCNI_EVENT6,
    HAL_CCNI_EVENT7,
    HAL_CCNI_EVENT8,
    HAL_CCNI_EVENT9,
    HAL_CCNI_EVENT10,
    HAL_CCNI_EVENT11,
    HAL_CCNI_EVENT12,
    HAL_CCNI_EVENT13,
    HAL_CCNI_EVENT14,
    HAL_CCNI_EVENT15,
    HAL_CCNI_EVENT16,
    HAL_CCNI_EVENT17,
    HAL_CCNI_EVENT18,
    HAL_CCNI_EVENT19,
    HAL_CCNI_EVENT20,
    HAL_CCNI_EVENT21,
    HAL_CCNI_EVENT22,
    HAL_CCNI_EVENT23,
    HAL_CCNI_EVENT24,
    HAL_CCNI_EVENT25,
    HAL_CCNI_EVENT26,
    HAL_CCNI_EVENT27,
    HAL_CCNI_EVENT28,
    HAL_CCNI_EVENT29,
    HAL_CCNI_EVENT30,
    HAL_CCNI_EVENT31,
    HAL_CCNI_EVENT_MAX
} hal_ccni_event_e;

#define    CCNI_CORE_NUMS                    2

#define    CCNI_EVENT_SRC_OFFSET             24
#define    CCNI_EVENT_SRC_MASK               (0xFF000000)
#define    CCNI_EVENT_SRC_MCU                (HAL_CCNI_CORE_MCU<<CCNI_EVENT_SRC_OFFSET)
#define    CCNI_EVENT_SRC_RISCV               (HAL_CCNI_CORE_RISCV<<CCNI_EVENT_SRC_OFFSET)

#define    CCNI_EVENT_DST_OFFSET             16
#define    CCNI_EVENT_DST_MASK               (0x00FF0000)
#define    CCNI_EVENT_DST_MCU                (HAL_CCNI_CORE_MCU<<CCNI_EVENT_DST_OFFSET)
#define    CCNI_EVENT_DST_RISCV               (HAL_CCNI_CORE_RISCV<<CCNI_EVENT_DST_OFFSET)

#define    CCNI_EVENT_IDX_MASK               (HAL_CCNI_EVENT_MAX - 1)


/**
 * @addtogroup HAL
 * @{
 * @addtogroup CCNI
 * @{
 * This section introduces how to define a CCNI event.
 */


/** @defgroup hal_ccni_define Define
  * @{
  *
  */

/***********************************************************************************************
 ****    MCU to RISCV event definition    *******************************************************
 ***********************************************************************************************/
#define    IRQGEN_MCU2RISCV_EVENT0            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT0)
#define    IRQGEN_MCU2RISCV_EVENT1            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT1)
#define    IRQGEN_MCU2RISCV_EVENT2            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT2)
#define    IRQGEN_MCU2RISCV_EVENT3            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT3)
#define    IRQGEN_MCU2RISCV_EVENT4            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT4)
#define    IRQGEN_MCU2RISCV_EVENT5            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT5)
#define    IRQGEN_MCU2RISCV_EVENT6            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT6)
#define    IRQGEN_MCU2RISCV_EVENT7            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT7)
#define    IRQGEN_MCU2RISCV_EVENT8            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT8)
#define    IRQGEN_MCU2RISCV_EVENT9            (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT9)
#define    IRQGEN_MCU2RISCV_EVENT10           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT10)
#define    IRQGEN_MCU2RISCV_EVENT11           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT11)
#define    IRQGEN_MCU2RISCV_EVENT12           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT12)
#define    IRQGEN_MCU2RISCV_EVENT13           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT13)
#define    IRQGEN_MCU2RISCV_EVENT14           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT14)
#define    IRQGEN_MCU2RISCV_EVENT15           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT15)
#define    IRQGEN_MCU2RISCV_EVENT16           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT16)
#define    IRQGEN_MCU2RISCV_EVENT17           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT17)
#define    IRQGEN_MCU2RISCV_EVENT18           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT18)
#define    IRQGEN_MCU2RISCV_EVENT19           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT19)
#define    IRQGEN_MCU2RISCV_EVENT20           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT20)
#define    IRQGEN_MCU2RISCV_EVENT21           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT21)
#define    IRQGEN_MCU2RISCV_EVENT22           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT22)
#define    IRQGEN_MCU2RISCV_EVENT23           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT23)
#define    IRQGEN_MCU2RISCV_EVENT24           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT24)
#define    IRQGEN_MCU2RISCV_EVENT25           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT25)
#define    IRQGEN_MCU2RISCV_EVENT26           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT26)
#define    IRQGEN_MCU2RISCV_EVENT27           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT27)
#define    IRQGEN_MCU2RISCV_EVENT28           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT28)
#define    IRQGEN_MCU2RISCV_EVENT29           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT29)
#define    IRQGEN_MCU2RISCV_EVENT30           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT30)
#define    IRQGEN_MCU2RISCV_EVENT31           (CCNI_EVENT_SRC_MCU|CCNI_EVENT_DST_RISCV|HAL_CCNI_EVENT31)


/***********************************************************************************************
 ****    RISCV to MCU event definition    *******************************************************
 ***********************************************************************************************/
#define    IRQGEN_RISCV2MCU_EVENT0            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT0)
#define    IRQGEN_RISCV2MCU_EVENT1            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT1)
#define    IRQGEN_RISCV2MCU_EVENT2            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT2)
#define    IRQGEN_RISCV2MCU_EVENT3            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT3)
#define    IRQGEN_RISCV2MCU_EVENT4            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT4)
#define    IRQGEN_RISCV2MCU_EVENT5            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT5)
#define    IRQGEN_RISCV2MCU_EVENT6            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT6)
#define    IRQGEN_RISCV2MCU_EVENT7            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT7)
#define    IRQGEN_RISCV2MCU_EVENT8            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT8)
#define    IRQGEN_RISCV2MCU_EVENT9            (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT9)
#define    IRQGEN_RISCV2MCU_EVENT10           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT10)
#define    IRQGEN_RISCV2MCU_EVENT11           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT11)
#define    IRQGEN_RISCV2MCU_EVENT12           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT12)
#define    IRQGEN_RISCV2MCU_EVENT13           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT13)
#define    IRQGEN_RISCV2MCU_EVENT14           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT14)
#define    IRQGEN_RISCV2MCU_EVENT15           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT15)
#define    IRQGEN_RISCV2MCU_EVENT16           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT16)
#define    IRQGEN_RISCV2MCU_EVENT17           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT17)
#define    IRQGEN_RISCV2MCU_EVENT18           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT18)
#define    IRQGEN_RISCV2MCU_EVENT19           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT19)
#define    IRQGEN_RISCV2MCU_EVENT20           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT20)
#define    IRQGEN_RISCV2MCU_EVENT21           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT21)
#define    IRQGEN_RISCV2MCU_EVENT22           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT22)
#define    IRQGEN_RISCV2MCU_EVENT23           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT23)
#define    IRQGEN_RISCV2MCU_EVENT24           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT24)
#define    IRQGEN_RISCV2MCU_EVENT25           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT25)
#define    IRQGEN_RISCV2MCU_EVENT26           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT26)
#define    IRQGEN_RISCV2MCU_EVENT27           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT27)
#define    IRQGEN_RISCV2MCU_EVENT28           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT28)
#define    IRQGEN_RISCV2MCU_EVENT29           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT29)
#define    IRQGEN_RISCV2MCU_EVENT30           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT30)
#define    IRQGEN_RISCV2MCU_EVENT31           (CCNI_EVENT_SRC_RISCV|CCNI_EVENT_DST_MCU|HAL_CCNI_EVENT31)


#ifdef __cplusplus
}
#endif

/**
 * @}
 */

/**
 * @}
 * @}
 */

#endif /*HAL_CCNI_MODULE_ENABLED*/
#endif /* __HAL_CCNI_CONFIG_H__ */

