
CONFIG_MCUBOOT_LOG_LEVEL_WRN=y
CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y

CONFIG_ARM_MPU=n
CONFIG_AIR_CACHE=y
CONFIG_AIR_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

CONFIG_BUILD_OUTPUT_HEX=y

CONFIG_TCM_BOOTING=y
CONFIG_FLASH_BOOTING=n
CONFIG_XIP=n
CONFIG_FLASH_SIZE=0
CONFIG_FLASH_BASE_ADDRESS=0x08000000

# firmware header is reset_handler because of BROM jump method
CONFIG_AIR_STD_ARM_BOOT_METHOD_ENABLE=n

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_BOOT_SIGNATURE_TYPE_AES=n
CONFIG_BOOT_HW_KEY=n
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=3072

# mcuboot should not using cross core memory
CONFIG_AIR_SOC_CROSS_CORE_MEMORY_ENABLE=n
CONFIG_AIR_CCNI=n

# single slot only
CONFIG_SINGLE_APPLICATION_SLOT=y

# the flash partitions used by mcuboot may be different from those used by the main firmware
# depending on the flash size of ab162x, the value of 512 may be appropriate
CONFIG_BOOT_MAX_IMG_SECTORS=512

# Enable FOTA
CONFIG_AIR_FOTA_ENABLE=y

# default uses USB DFU, set CONFIG_AIR_BL_UART_DFU_ENABLE=y for UART
CONFIG_AIR_BL_DFU_ENABLE=y
CONFIG_AIR_BL_UART_DFU_ENABLE=y

# NOTE: The basic USB Config is binding to AIR_BL_USB_HID_DFU_ENABLE
# e.g. USB_DEVICE_STACK & USB_DEVICE_HID
# USB General Settings
# CONFIG_USB_DEVICE_PRODUCT="Airoha USB HID DFU Device"
# CONFIG_USB_DEVICE_MANUFACTURER=""
# CONFIG_USB_DEVICE_VID=0x0E8D
# CONFIG_USB_DEVICE_PID=0x0004

# USB Detail Settings
# CONFIG_USB_REQUEST_BUFFER_SIZE=1024
# CONFIG_USB_AIROHA_ATTACHED_EVENT_DELAY=0

# USB HID Settings
# CONFIG_USB_HID_DEVICE_COUNT=1
# CONFIG_ENABLE_HID_INT_OUT_EP=n
# CONFIG_USB_HID_BOOT_PROTOCOL=n
# CONFIG_USB_HID_POLL_INTERVAL_MS=1
# CONFIG_HID_INTERRUPT_EP_MPS=64
# CONFIG_USB_HID_REPORTS=1

# USB Debug Log
# CONFIG_USB_DEVICE_LOG_LEVEL_DBG=n
# CONFIG_USB_HID_LOG_LEVEL_DBG=n

# Airoha USB Subsys Config
# CONFIG_AIR_USB_ENABLE=y
# CONFIG_AIR_USB_HID_ENABLE=y

CONFIG_WRAP_PRINTK=n

CONFIG_AIR_FOTA_UPGRADE_ENABLE=n