/* Copyright Statement:
 *
 * (C) 2023  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors
 * any reproduction  modification  use or disclosure of Airoha Software
 * and information contained herein  in whole or in part  shall be strictly prohibited.
 * You may only use  reproduce  modify  or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE  RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES  EXPRESS OR IMPLIED  INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY  FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY  INCORPORATED IN  OR
 * SUPPLIED WITH AIROHA SOFTWARE  AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE
 * AT AIROHA'S OPTION  TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __NVKEY_ID_DEFINITION_H__
#define __NVKEY_ID_DEFINITION_H__

#include <stdio.h>

/* The valid NVKEY range is from 0x0001 to 0x7FFF.
 * NVKEY is based on NVS & Settings, and settings item may use ids from 0x8000 to 0xFFFF.
 * In order to preserve the software flexibility that there are multiple non-volatile data partitions
 * to store data, it is recommended to directly distinguish the OTA-capable area from
 * the non-OTA area from the ID.
 *     0x0001 ~ 0x5FFF => NVID items can be OTA
 *     0x6000 ~ 0x7FFF => NVID items cannot be OTA
 * In other words, NVID and Settings that cannot be used by OTA share the same partition to store data,
 * and NVID that can be used by OTA may have a separate partition to store data.
 */

/* Directly use uint16_t to explicitly specify the parameter type instead of
 * using NVKey_ID_list to avoid portability problems caused by
 * different compilation options of enum.
 */
#define      NVID_CAN_BE_OTA_BEGIN                              ((uint16_t)0x0001)
#define      NVID_CAN_BE_OTA_END                                ((uint16_t)0x5FFF)

#define      NVID_CANNOT_BE_OTA_BEGIN                           ((uint16_t)0x6000)
#define      NVID_CANNOT_BE_OTA_END                             ((uint16_t)0x7FFF)

typedef enum {
    NVID_NVDM_VERSION                                  = 0x1001,
    NVID_PRODUCT_CATEGORY                              = 0x1002,
    NVID_BT_HOST_RELAY_ENABLE                          = 0x1839,
    NVID_HQA_VOLT_CFG                                  = 0x200C,
    NVID_CAL_VBAT_ADC_CAL_TABLE                        = 0x2020,
    NVID_CAL_VBAT_VOLT_CFG                             = 0x2021,
    NVID_CAL_XO_CAPID                                  = 0x2045,
    NVID_FG_DATA                                       = 0x204F,
    NVID_FG_CFG                                        = 0x2050,
    NVID_BT_HOST_LOCAL_ADDR                            = 0x3601,
    NVID_RF_MISC_PWR_CTL                               = 0x3720,
    NVID_RF_BR_DAC_IBIAS_TABLE                         = 0x3721,
    NVID_RF_EDR_DAC_IBIAS_TABLE                        = 0x3722,
    NVID_RF_BR_DPC_TABLE_K_V12                         = 0x3723,
    NVID_RF_EDR_DPC_TABLE_K_V12                        = 0x3724,
    NVID_RF_BR_TX_GAIN_TABLE_K_V12                     = 0x3727,
    NVID_RF_EDR_TX_GAIN_TABLE_K_V12                    = 0x3728,
    NVID_RF_BR_DPC_TABLE_K_V14                         = 0x3730,
    NVID_RF_EDR_DPC_TABLE_K_V14                        = 0x3731,
    NVID_RF_BR_DPC_TABLE_K_V16                         = 0x3732,
    NVID_RF_EDR_DPC_TABLE_K_V16                        = 0x3733,
    NVID_RF_BR_DPC_TABLE_K_V18                         = 0x3734,
    NVID_RF_EDR_DPC_TABLE_K_V18                        = 0x3735,
    NVID_RF_BR_DPC_TABLE_K_V22                         = 0x3736,
    NVID_RF_EDR_DPC_TABLE_K_V22                        = 0x3737,
    NVID_RF_BR_TX_GAIN_TABLE_K_V14                     = 0x3738,
    NVID_RF_EDR_TX_GAIN_TABLE_K_V14                    = 0x3739,
    NVID_RF_BR_TX_GAIN_TABLE_K_V16                     = 0x373A,
    NVID_RF_EDR_TX_GAIN_TABLE_K_V16                    = 0x373B,
    NVID_RF_BR_TX_GAIN_TABLE_K_V18                     = 0x373C,
    NVID_RF_EDR_TX_GAIN_TABLE_K_V18                    = 0x373D,
    NVID_RF_BR_TX_GAIN_TABLE_K_V22                     = 0x373E,
    NVID_RF_EDR_TX_GAIN_TABLE_K_V22                    = 0x373F,
    NVID_RF_TX_GAIN_TABLE_K_0V96                       = 0x3740,
    NVID_RF_TX_GAIN_TABLE_K_1V2                        = 0x3741,
    NVID_RF_TX_GAIN_TABLE_K_1V45                       = 0x3742,
    NVID_RF_AM_TABLE_K_0V96                            = 0x3743,
    NVID_RF_AM_TABLE_K_1V2                             = 0x3744,
    NVID_RF_AM_TABLE_K_1V45                            = 0x3745,
    NVID_VPA_VOLTAGE                                   = 0x3746,
    NVID_RF_802154_CHANNEL_THRESHOLD                   = 0x3747,
    NVID_RF_LE_CHANNEL_THRESHOLD                       = 0x3748,
    NVID_802154_CCA_THRESHOLD                          = 0x3749,
    NVID_802154_CCA_DURATION                           = 0x374a,
    NVID_802154_CCA_TURNAROUND_TIME                    = 0x374b,
    NVID_RF_0V96_TXGC                                  = 0x3755,
    NVID_RF_1V2_TXGC                                   = 0x3756,
    NVID_RF_1V45_TXGC                                  = 0x3757,
    NVID_RF_PWR_CTL                                    = 0x3758,
    NVID_RF_802154_0V96_TXGC                           = 0x3759,
    NVID_RF_802154_1V2_TXGC                            = 0x375a,
    NVID_RF_802154_1V45_TXGC                           = 0x375b,
    NVID_RF_D4_TEST_MODE_EN                            = 0x375c,
    NVID_PERI_LOG_SETTING                              = 0x4007,
    NVID_PERI_LOG_MODULE_SETTING                       = 0x4008,
    NVID_PERI_LOG_CPU_SETTING                          = 0x4009,
    NVID_SYS_EXP_DUMP_MODE                             = 0x4010,
    NVID_APP_FIND_MY_PRODUCT_DATA                      = 0x4011,
    NVID_APP_FIND_MY_UUID                              = 0x4012,
    NVID_APP_FIND_MY_TOKEN                             = 0x4013,
    NVID_APP_FIND_MY_SN                                = 0x4014,
    NVID_APP_FIND_MY_CONTEXT                           = 0x4015,
    NVID_APP_FIND_MY_ROLL_KEY                          = 0x4016,
    NVID_APP_FIND_MY_OWNER_PHONE_INFO                  = 0x4017,
    NVID_APP_DYNAMIC_POWER_CONTROL_INFO                = 0x4080,
    NVID_APP_POWER_CONTROL_MODE                        = 0x4081,
    NVID_SYS_MUX_PORT_USER                             = 0x4090,
    NVID_BT_HOST_ULL_HID_KB_INFO                       = 0x4300,
    NVID_BT_HOST_ULL_HID_MS_INFO                       = 0x4301,
    NVID_BT_HOST_ULL_HID_GP_INFO                       = 0x4302,
    NVID_BT_HOST_ULL_HID_LOCAL_ADDRESS                 = 0x4310,
    NVID_POWER_SAVING_TIMEOUT                          = 0x6000,
    NVID_DYNAMIC_PINMUX_CONFIG                         = 0x6001,
    NVID_HID_APP_FEATURES                              = 0x6002,
    NVID_HID_USB_FEATURES                              = 0x6003,
    NVID_HID_SENSOR_FEATURES                           = 0x6004,
    NVID_HID_EXPRESS_FEATURES                          = 0x6005,
    NVID_HID_REPORT_RATE_IDX                           = 0x6005,
    NVID_LINK_IDX                                      = 0x6010,
    NVID_DEBOUNCE_TIME_LIST                            = 0x6011,
    NVID_SW_DEBOUNCE_TIME_LIST                         = 0x6012,
    NVID_LINEAR_REMAP_THRESHOLD_1                      = 0x6040,
    NVID_LINEAR_REMAP_THRESHOLD_2                      = 0x6041,
    NVID_LINEAR_REMAP_THRESHOLD_3                      = 0x6042,
    NVID_LINEAR_REMAP_THRESHOLD_4                      = 0x6043,
    NVID_LOCAL_DEVICES_ADDR_ID_0                       = 0x6100,
    NVID_LOCAL_DEVICES_ADDR_ID_1                       = 0x6101,
    NVID_LOCAL_DEVICES_ADDR_ID_2                       = 0x6102,
    NVID_LOCAL_DEVICES_ADDR_ID_3                       = 0x6103,
    NVID_LOCAL_DEVICES_ADDR_ID_4                       = 0x6104,
    NVID_LOCAL_DEVICES_ADDR_ID_5                       = 0x6105,
    NVID_LOCAL_DEVICES_ADDR_ID_6                       = 0x6106,
    NVID_LOCAL_DEVICES_ADDR_ID_7                       = 0x6107,
    NVID_GAMING_MODE_PEER_DEVICE_INFO_0                = 0x6110,
    NVID_GAMING_MODE_PEER_DEVICE_INFO_1                = 0x6111,
    NVID_GAMING_MODE_PEER_DEVICE_INFO_2                = 0x6112,
    NVID_GAMING_MODE_PEER_DEVICE_INFO_3                = 0x6113,
    NVID_BT_MODE_PEER_DEVICE_ADDR_0                    = 0x6114,
    NVID_BT_MODE_PEER_DEVICE_ADDR_1                    = 0x6115,
    NVID_BT_MODE_PEER_DEVICE_ADDR_2                    = 0x6116,
    NVID_BT_MODE_PEER_DEVICE_ADDR_3                    = 0x6117,
    NVID_REPORT_RATE_LIST_0                            = 0x6118,
    NVID_REPORT_RATE_LIST_1                            = 0x6119,
    NVID_DPI_SETTING_LIST_1                            = 0x6120,
    NVID_DPI_SETTING_LIST_2                            = 0x6121,
    NVID_DPI_SETTING_LIST_3                            = 0x6122,
    NVID_DPI_SETTING_LIST_4                            = 0x6123,
    NVID_SENSOR_ATTR_SETTING_1                         = 0x6128,
    NVID_SENSOR_ATTR_SETTING_2                         = 0x6129,
    NVID_SENSOR_ATTR_SETTING_3                         = 0x612A,
    NVID_SENSOR_ATTR_SETTING_4                         = 0x612B,
    NVID_KEY_REMAP_MACRO_1_1                           = 0x6130,
    NVID_KEY_REMAP_MACRO_1_2                           = 0x6131,
    NVID_KEY_REMAP_MACRO_1_3                           = 0x6132,
    NVID_KEY_REMAP_MACRO_1_4                           = 0x6133,
    NVID_KEY_REMAP_MACRO_1_5                           = 0x6134,
    NVID_KEY_REMAP_MACRO_1_6                           = 0x6135,
    NVID_KEY_REMAP_MACRO_1_7                           = 0x6136,
    NVID_KEY_REMAP_MACRO_1_8                           = 0x6137,
    NVID_KEY_REMAP_MACRO_2_1                           = 0x6138,
    NVID_KEY_REMAP_MACRO_2_2                           = 0x6139,
    NVID_KEY_REMAP_MACRO_2_3                           = 0x613A,
    NVID_KEY_REMAP_MACRO_2_4                           = 0x613B,
    NVID_KEY_REMAP_MACRO_2_5                           = 0x613C,
    NVID_KEY_REMAP_MACRO_2_6                           = 0x613D,
    NVID_KEY_REMAP_MACRO_2_7                           = 0x613E,
    NVID_KEY_REMAP_MACRO_2_8                           = 0x613F,
    NVID_KEY_REMAP_MACRO_3_1                           = 0x6140,
    NVID_KEY_REMAP_MACRO_3_2                           = 0x6141,
    NVID_KEY_REMAP_MACRO_3_3                           = 0x6142,
    NVID_KEY_REMAP_MACRO_3_4                           = 0x6143,
    NVID_KEY_REMAP_MACRO_3_5                           = 0x6144,
    NVID_KEY_REMAP_MACRO_3_6                           = 0x6145,
    NVID_KEY_REMAP_MACRO_3_7                           = 0x6146,
    NVID_KEY_REMAP_MACRO_3_8                           = 0x6147,
    NVID_KEY_REMAP_MACRO_4_1                           = 0x6148,
    NVID_KEY_REMAP_MACRO_4_2                           = 0x6149,
    NVID_KEY_REMAP_MACRO_4_3                           = 0x614A,
    NVID_KEY_REMAP_MACRO_4_4                           = 0x614B,
    NVID_KEY_REMAP_MACRO_4_5                           = 0x614C,
    NVID_KEY_REMAP_MACRO_4_6                           = 0x614D,
    NVID_KEY_REMAP_MACRO_4_7                           = 0x614E,
    NVID_KEY_REMAP_MACRO_4_8                           = 0x614F,
    NVID_KEY_REMAP_FN_KEY_1                            = 0x6150,
    NVID_KEY_REMAP_FN_KEY_2                            = 0x6151,
    NVID_KEY_REMAP_FN_KEY_3                            = 0x6152,
    NVID_KEY_REMAP_FN_KEY_4                            = 0x6153,
    NVID_KEY_REMAP_PROFILE_1                           = 0x6160,
    NVID_KEY_REMAP_PROFILE_2                           = 0x6161,
    NVID_KEY_REMAP_PROFILE_3                           = 0x6162,
    NVID_KEY_REMAP_PROFILE_4                           = 0x6163,
    NVID_PROFILE_ID                                    = 0x6168,
    NVID_FACTORY_RESET                                 = 0x6169,
    NVID_FAKE_REPORT_STATUS                            = 0x6170,
    NVID_KEY_REMAP_MACRO_1_9                           = 0x6180,
    NVID_KEY_REMAP_MACRO_1_10                          = 0x6181,
    NVID_KEY_REMAP_MACRO_1_11                          = 0x6182,
    NVID_KEY_REMAP_MACRO_1_12                          = 0x6183,
    NVID_KEY_REMAP_MACRO_1_13                          = 0x6184,
    NVID_KEY_REMAP_MACRO_2_9                           = 0x6185,
    NVID_KEY_REMAP_MACRO_2_10                          = 0x6186,
    NVID_KEY_REMAP_MACRO_2_11                          = 0x6187,
    NVID_KEY_REMAP_MACRO_2_12                          = 0x6188,
    NVID_KEY_REMAP_MACRO_2_13                          = 0x6189,
    NVID_KEY_REMAP_MACRO_3_9                           = 0x618A,
    NVID_KEY_REMAP_MACRO_3_10                          = 0x618B,
    NVID_KEY_REMAP_MACRO_3_11                          = 0x618C,
    NVID_KEY_REMAP_MACRO_3_12                          = 0x618D,
    NVID_KEY_REMAP_MACRO_3_13                          = 0x618E,
    NVID_KEY_REMAP_MACRO_4_9                           = 0x618F,
    NVID_KEY_REMAP_MACRO_4_10                          = 0x6190,
    NVID_KEY_REMAP_MACRO_4_11                          = 0x6191,
    NVID_KEY_REMAP_MACRO_4_12                          = 0x6192,
    NVID_KEY_REMAP_MACRO_4_13                          = 0x6193,
    NVID_RGB_ID_0_DATA0                                = 0x6200,
    NVID_RGB_ID_0_DATA1                                = 0x6201,
    NVID_RGB_ID_0_DATA2                                = 0x6202,
    NVID_RGB_ID_0_DATA3                                = 0x6203,
    NVID_RGB_ID_0_DATA4                                = 0x6204,
    NVID_RGB_ID_0_DATA5                                = 0x6205,
    NVID_RGB_ID_0_DATA6                                = 0x6206,
    NVID_RGB_ID_0_DATA7                                = 0x6207,
    NVID_RGB_ID_1_DATA0                                = 0x6208,
    NVID_RGB_ID_1_DATA1                                = 0x6209,
    NVID_RGB_ID_1_DATA2                                = 0x620A,
    NVID_RGB_ID_1_DATA3                                = 0x620B,
    NVID_RGB_ID_1_DATA4                                = 0x620C,
    NVID_RGB_ID_1_DATA5                                = 0x620D,
    NVID_RGB_ID_1_DATA6                                = 0x620E,
    NVID_RGB_ID_1_DATA7                                = 0x620F,
    NVID_RGB_ID_2_DATA0                                = 0x6210,
    NVID_RGB_ID_2_DATA1                                = 0x6211,
    NVID_RGB_ID_2_DATA2                                = 0x6212,
    NVID_RGB_ID_2_DATA3                                = 0x6213,
    NVID_RGB_ID_2_DATA4                                = 0x6214,
    NVID_RGB_ID_2_DATA5                                = 0x6215,
    NVID_RGB_ID_2_DATA6                                = 0x6216,
    NVID_RGB_ID_2_DATA7                                = 0x6217,
    NVID_RGB_ID_3_DATA0                                = 0x6218,
    NVID_RGB_ID_3_DATA1                                = 0x6219,
    NVID_RGB_ID_3_DATA2                                = 0x621A,
    NVID_RGB_ID_3_DATA3                                = 0x621B,
    NVID_RGB_ID_3_DATA4                                = 0x621C,
    NVID_RGB_ID_3_DATA5                                = 0x621D,
    NVID_RGB_ID_3_DATA6                                = 0x621E,
    NVID_RGB_ID_3_DATA7                                = 0x621F,
    NVID_RGB_DEFAULT_FLASH                             = 0x6220,
    NVID_APP_FOTA_RECOED_RR                            = 0x6250,
    NVID_APP_LE_RANDOM_ADDRESS                         = 0x6280,
    NVID_APP_MULTI_ADV_LE_ADDR                         = 0x6300,
    NVID_APP_GAME_CONTROLLER_JOYSTICK_X                = 0x6400,
    NVID_APP_GAME_CONTROLLER_JOYSTICK_Y                = 0x6401,
    NVID_APP_GAME_CONTROLLER_JOYSTICK_Z                = 0x6402,
    NVID_APP_GAME_CONTROLLER_JOYSTICK_RZ               = 0x6403,
    NVID_APP_GAME_CONTROLLER_TRIGGER_L                 = 0x6410,
    NVID_APP_GAME_CONTROLLER_TRIGGER_R                 = 0x6411,
    NVID_APP_FPS_SPOT_UNTRACKING_MODE                  = 0x6420,
    NVID_APP_FPS_SPOT_EIK                              = 0x6421,
    NVID_APP_FPS_SPOT_LAST_EID                         = 0x6422,
    NVID_APP_FPS_SPOT_EID_COUNTER                      = 0x6423,
    NVID_APP_FAST_PAIR_CONFIGURE                       = 0x6425,
    NVID_APP_FAST_PAIR_PROTECTED                       = 0x6426,
    NVID_APP_FAST_PAIR_ACCOUNT_KEY                     = 0x6427,
    NVID_APP_DONGLE_ULL2_HID_SCENARIO                  = 0x6600,
    NVID_APP_USB_MODE                                  = 0x6601,
    NVID_APP_DONGLE_CM_DEVICE_LIST                     = 0x6602,
    NVID_APP_DONGLE_CM_LAST_LINK_TYPE                  = 0x6603,
    NVID_KEY_REMAP_MACRO_1_14                          = 0x6700,
    NVID_KEY_REMAP_MACRO_1_15                          = 0x6701,
    NVID_KEY_REMAP_MACRO_1_16                          = 0x6702,
    NVID_KEY_REMAP_MACRO_1_17                          = 0x6703,
    NVID_KEY_REMAP_MACRO_1_18                          = 0x6704,
    NVID_KEY_REMAP_MACRO_1_19                          = 0x6705,
    NVID_KEY_REMAP_MACRO_1_20                          = 0x6706,
    NVID_KEY_REMAP_MACRO_1_21                          = 0x6707,
    NVID_KEY_REMAP_MACRO_1_22                          = 0x6708,
    NVID_KEY_REMAP_MACRO_1_23                          = 0x6709,
    NVID_KEY_REMAP_MACRO_1_24                          = 0x670A,
    NVID_KEY_REMAP_MACRO_1_25                          = 0x670B,
    NVID_KEY_REMAP_MACRO_1_26                          = 0x670C,
    NVID_KEY_REMAP_MACRO_1_27                          = 0x670D,
    NVID_KEY_REMAP_MACRO_1_28                          = 0x670E,
    NVID_KEY_REMAP_MACRO_1_29                          = 0x670F,
    NVID_KEY_REMAP_MACRO_1_30                          = 0x6710,
    NVID_KEY_REMAP_MACRO_1_31                          = 0x6711,
    NVID_KEY_REMAP_MACRO_1_32                          = 0x6712,
    NVID_KEY_REMAP_MACRO_1_33                          = 0x6713,
    NVID_KEY_REMAP_MACRO_1_34                          = 0x6714,
    NVID_KEY_REMAP_MACRO_1_35                          = 0x6715,
    NVID_KEY_REMAP_MACRO_1_36                          = 0x6716,
    NVID_KEY_REMAP_MACRO_2_14                          = 0x6758,
    NVID_KEY_REMAP_MACRO_2_15                          = 0x6759,
    NVID_KEY_REMAP_MACRO_2_16                          = 0x675A,
    NVID_KEY_REMAP_MACRO_2_17                          = 0x675B,
    NVID_KEY_REMAP_MACRO_2_18                          = 0x675C,
    NVID_KEY_REMAP_MACRO_2_19                          = 0x675D,
    NVID_KEY_REMAP_MACRO_2_20                          = 0x675E,
    NVID_KEY_REMAP_MACRO_2_21                          = 0x675F,
    NVID_KEY_REMAP_MACRO_2_22                          = 0x6760,
    NVID_KEY_REMAP_MACRO_2_23                          = 0x6761,
    NVID_KEY_REMAP_MACRO_2_24                          = 0x6762,
    NVID_KEY_REMAP_MACRO_2_25                          = 0x6763,
    NVID_KEY_REMAP_MACRO_2_26                          = 0x6764,
    NVID_KEY_REMAP_MACRO_2_27                          = 0x6765,
    NVID_KEY_REMAP_MACRO_2_28                          = 0x6766,
    NVID_KEY_REMAP_MACRO_2_29                          = 0x6767,
    NVID_KEY_REMAP_MACRO_2_30                          = 0x6768,
    NVID_KEY_REMAP_MACRO_2_31                          = 0x6769,
    NVID_KEY_REMAP_MACRO_2_32                          = 0x676A,
    NVID_KEY_REMAP_MACRO_2_33                          = 0x676B,
    NVID_KEY_REMAP_MACRO_2_34                          = 0x676C,
    NVID_KEY_REMAP_MACRO_2_35                          = 0x676D,
    NVID_KEY_REMAP_MACRO_2_36                          = 0x676E,
    NVID_KEY_REMAP_MACRO_3_14                          = 0x67B0,
    NVID_KEY_REMAP_MACRO_3_15                          = 0x67B1,
    NVID_KEY_REMAP_MACRO_3_16                          = 0x67B2,
    NVID_KEY_REMAP_MACRO_3_17                          = 0x67B3,
    NVID_KEY_REMAP_MACRO_3_18                          = 0x67B4,
    NVID_KEY_REMAP_MACRO_3_19                          = 0x67B5,
    NVID_KEY_REMAP_MACRO_3_20                          = 0x67B6,
    NVID_KEY_REMAP_MACRO_3_21                          = 0x67B7,
    NVID_KEY_REMAP_MACRO_3_22                          = 0x67B8,
    NVID_KEY_REMAP_MACRO_3_23                          = 0x67B9,
    NVID_KEY_REMAP_MACRO_3_24                          = 0x67BA,
    NVID_KEY_REMAP_MACRO_3_25                          = 0x67BB,
    NVID_KEY_REMAP_MACRO_3_26                          = 0x67BC,
    NVID_KEY_REMAP_MACRO_3_27                          = 0x67BD,
    NVID_KEY_REMAP_MACRO_3_28                          = 0x67BE,
    NVID_KEY_REMAP_MACRO_3_29                          = 0x67BF,
    NVID_KEY_REMAP_MACRO_3_30                          = 0x67C0,
    NVID_KEY_REMAP_MACRO_3_31                          = 0x67C1,
    NVID_KEY_REMAP_MACRO_3_32                          = 0x67C2,
    NVID_KEY_REMAP_MACRO_3_33                          = 0x67C3,
    NVID_KEY_REMAP_MACRO_3_34                          = 0x67C4,
    NVID_KEY_REMAP_MACRO_3_35                          = 0x67C5,
    NVID_KEY_REMAP_MACRO_3_36                          = 0x67C6,
    NVID_KEY_REMAP_MACRO_4_14                          = 0x6808,
    NVID_KEY_REMAP_MACRO_4_15                          = 0x6809,
    NVID_KEY_REMAP_MACRO_4_16                          = 0x680A,
    NVID_KEY_REMAP_MACRO_4_17                          = 0x680B,
    NVID_KEY_REMAP_MACRO_4_18                          = 0x680C,
    NVID_KEY_REMAP_MACRO_4_19                          = 0x680D,
    NVID_KEY_REMAP_MACRO_4_20                          = 0x680E,
    NVID_KEY_REMAP_MACRO_4_21                          = 0x680F,
    NVID_KEY_REMAP_MACRO_4_22                          = 0x6810,
    NVID_KEY_REMAP_MACRO_4_23                          = 0x6811,
    NVID_KEY_REMAP_MACRO_4_24                          = 0x6812,
    NVID_KEY_REMAP_MACRO_4_25                          = 0x6813,
    NVID_KEY_REMAP_MACRO_4_26                          = 0x6814,
    NVID_KEY_REMAP_MACRO_4_27                          = 0x6815,
    NVID_KEY_REMAP_MACRO_4_28                          = 0x6816,
    NVID_KEY_REMAP_MACRO_4_29                          = 0x6817,
    NVID_KEY_REMAP_MACRO_4_30                          = 0x6818,
    NVID_KEY_REMAP_MACRO_4_31                          = 0x6819,
    NVID_KEY_REMAP_MACRO_4_32                          = 0x681A,
    NVID_KEY_REMAP_MACRO_4_33                          = 0x681B,
    NVID_KEY_REMAP_MACRO_4_34                          = 0x681C,
    NVID_KEY_REMAP_MACRO_4_35                          = 0x681D,
    NVID_KEY_REMAP_MACRO_4_36                          = 0x681E,
    NVID_BT_HOST_ZB_MAC_ADDR                           = 0x4302,
    NVID_BT_ESL                                        = 0x4303,
    NVID_BT_DIS_SERVICE                                = 0x4304,
} NVKey_ID_list;

#endif /* __NVKEY_ID_DEFINITION_H__ */
