/* Copyright Statement:
 *
 * (C) 2025  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
 * RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED
 * TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#define CONFIG_UART_EARLY_INIT_LEVEL EARLY

#define CONFIG_INTC_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_FLASH_CFG_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_FPGA_CLOCK_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_CLOCK_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_GPIO_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_PINMUX_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_CCM_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_CORE_STATUS_BOOT_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_SERIAL_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_LOG_EARLY_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_SLEEP_MANAGER_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_RAM_BLOCKS_CONTROL_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_PD_DOMAIN_CONTROL_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_I2C_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_SPIM_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_SPIS_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_TRNG_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_CACHE_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_FLASH_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_ESC_DEVICE_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_PARTITION_TABLE_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_PWM_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_PWM_DMA_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_LED_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_CCNI_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_RTC_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_IRRX_INIT_LEVEL PRE_KERNEL_1
#define CONFIG_MOUSE_SENSOR_PREINIT_LEVEL PRE_KERNEL_1

#define CONFIG_NVDATA_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_PMU_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_BATTER_MANAGEMENT_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_DCXO_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_DVFS_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_LOG_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_EXCEPTION_DUMP_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_OFFLINE_DUMP_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_BOOT_REASON_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_SYS_HANG_TRACER_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_USB_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_WDT_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_OST_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_SWLA_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_MOUSE_SENSOR_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_IO_EXPANDER_SENSOR_INIT_LEVEL PRE_KERNEL_2
#define CONFIG_START_RISCV_INIT_LEVEL PRE_KERNEL_2

#define CONFIG_DAEMON_WORK_Q_INIT_LEVEL POST_KERNEL
#define CONFIG_SHELL_BACKEND_SERIAL_INIT_LEVEL POST_KERNEL
#define CONFIG_USB_VBUS_DETECT_INIT_LEVEL POST_KERNEL
#define CONFIG_IEEE802154_INIT_LEVEL POST_KERNEL
#define CONFIG_RACE_CMD_INIT_LEVEL POST_KERNEL
#define CONFIG_SAR_ADC_INIT_LEVEL POST_KERNEL
#define CONFIG_AIOADC_INIT_LEVEL POST_KERNEL
#define CONFIG_MPU_INIT_LEVEL POST_KERNEL

#define CONFIG_DVFS_INIT_END_LEVEL APPLICATION
#define CONFIG_BUILD_INFO_INIT_LEVEL APPLICATION
#define CONFIG_CORE_STATUS_ACTIVE_INIT_LEVEL APPLICATION
