# Custom configuration

CONFIG_ASSERT=y

CONFIG_AIR_GPIO=n

CONFIG_AIR_FLASH=y

# UART feature
CONFIG_SERIAL=y
CONFIG_AIR_UART=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_AIR_RACE_CMD_ENABLE=y

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_MULTITHREADING=y

CONFIG_AIR_AVM=y
CONFIG_AIR_SWLA_ENABLE=n

CONFIG_BT=y
CONFIG_BT_HCI_ACL_FLOW_CONTROL=n

CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_SMP=y
CONFIG_BT_SMP_OOB_LEGACY_PAIR_ONLY=n
CONFIG_BT_DIS=y
CONFIG_BT_BAS=y
CONFIG_BT_DEVICE_NAME="Airoha Gaming Dongle"
CONFIG_BT_DEVICE_APPEARANCE=0

# airoha exclusive
CONFIG_AIR_SWLA_ENABLE=n
CONFIG_AIR_HW_SEMAPHORE=y
CONFIG_AIR_PKA_SHARE_ENABLE=y

CONFIG_AIR_PARTITION_GEN_TABLE_ENABLE=y

CONFIG_OUTPUT_DISASSEMBLY=n
CONFIG_OUTPUT_DISASSEMBLE_ALL=n

CONFIG_THREAD_NAME=y
CONFIG_THREAD_MAX_NAME_LEN=8

CONFIG_TINYCRYPT=y
CONFIG_TINYCRYPT_SHA256_HMAC=y
CONFIG_TINYCRYPT_ECC_DH=y
CONFIG_TINYCRYPT_AES_CTR=y

# generated configs.c depends on FLASH_SIZE & FLASH_BASE_ADDRESS
# FLASH_SIZE & FLASH_BASE_ADDRESS depends on XIP
# So if XIP is not choose, FLASH_SIZE needs to be changed to 0 because of linker.ld template
CONFIG_XIP=n
CONFIG_TCM_BOOTING=y
CONFIG_FLASH_SIZE=0
CONFIG_FLASH_BASE_ADDRESS=0x08000000

CONFIG_PRINTK_SYNC=y

# logging
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_FRONTEND=y
CONFIG_LOG_FRONTEND_ONLY=y
CONFIG_AIR_LOGGING_ENABLE=y
CONFIG_AIR_SHARE_BUFFER_ENABLE=y

# Airoha Exception Handler
CONFIG_AIR_EXCEPTION_HANDLER_ENABLE=y

# generate default nvkey binary file
CONFIG_AIR_NVKEY_ENABLE=y
CONFIG_GEN_DEFAULT_NVS_BIN=y
CONFIG_NVS_REPEAT_STRATEGY_USE_LAST=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_SETTINGS_DYNAMIC_HANDLERS=n