# Copyright Statement:
#
# (C) 2025  Airoha Technology Corp. All rights reserved.
#
# This software/firmware and related documentation ("Airoha Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
# Without the prior written permission of Airoha and/or its licensors,
# any reproduction, modification, use or disclosure of Airoha Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.
# You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
# if you have agreed to and been bound by the applicable license agreement with
# Airoha ("License Agreement") and been granted explicit permission to do so within
# the License Agreement ("Permitted User").  If you are not a Permitted User,
# please cease any access or use of Airoha Software immediately.
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
# RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED
# TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
# WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
# AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
#
# Custom configuration

CONFIG_LOG=n
CONFIG_ASSERT=y

#pinmux
CONFIG_GPIO=y
CONFIG_AIR_GPIO=y
CONFIG_PINCTRL=y
CONFIG_AIR_PINCTRL=y

#i2c
CONFIG_AIR_I2C=y
CONFIG_I2C=y
CONFIG_I2C_TARGET=y
CONFIG_SENSOR=y

# logging depend on AIR_UART
CONFIG_SERIAL=y
CONFIG_AIR_UART=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=2048

# Turn off multithreading, only main
CONFIG_MULTITHREADING=n
CONFIG_TIMESLICING=n

# secure firmware
CONFIG_TRUSTED_EXECUTION_SECURE=y

# cannot use NVS because of single thread cannot use mutex
CONFIG_NVS=n
CONFIG_SETTINGS=n
CONFIG_SETTINGS_NVS=n
CONFIG_SETTINGS_DYNAMIC_HANDLERS=n

# generate default nvkey binary file, has nvkey api but need to implement as return not support
CONFIG_AIR_NVKEY_ENABLE=y
CONFIG_GEN_DEFAULT_NVS_BIN=y
CONFIG_NVS_REPEAT_STRATEGY_USE_LAST=y

CONFIG_AIR_PARTITION_GEN_TABLE_ENABLE=y

CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_OUTPUT_DISASSEMBLE_ALL=n

CONFIG_WRAP_PRINTK=n

CONFIG_AIR_RISCV_PROJ_PATH="projects/templates/hello_world"
CONFIG_AIR_RISCV_FEATURE="config/feature.mk"

CONFIG_AIR_TRNG_ENABLE=y
CONFIG_AIR_ENTROPY_ENABLE=y


CONFIG_AIR_FLASH=y
CONFIG_FLASH_BOOTING=y

# logging
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_FRONTEND=y
CONFIG_LOG_FRONTEND_ONLY=y
CONFIG_AIR_LOGGING_ENABLE=y
CONFIG_AIR_SHARE_BUFFER_ENABLE=y

# Airoha Exception Handler
CONFIG_AIR_CCNI=y
CONFIG_AIR_HW_SEMAPHORE=y
CONFIG_AIR_EXCEPTION_HANDLER_ENABLE=y

# disable tracing, or else there is a build error at swap_helper.S
CONFIG_TRACING=n