/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __HID_KEYCODE_TABLE_HH_
#define __HID_KEYCODE_TABLE_HH_

#include "hid_common.h"

#define FN_KEY_FLAG   15    //Should not mix up with HID Report id. e.g. REPORT_ID_KB_STD, REPORT_ID_KB_CONSUMER

#define KEYCODE_FLAG_STD_KEY            (REPORT_ID_KB_STD << 12)
#define KEYCODE_FLAG_CONSUMER_KEY       (REPORT_ID_KB_CONSUMER << 12)
#define KEYCODE_FLAG_FUNCTION_POINTER   (FN_KEY_FLAG << 12)

#define    KC_NO                       (0x00 | KEYCODE_FLAG_STD_KEY)
#define    KC_ROLL_OVER                (0x01 | KEYCODE_FLAG_STD_KEY)
#define    KC_POST_FAIL                (0x02 | KEYCODE_FLAG_STD_KEY)
#define    KC_UNDEFINED                (0x03 | KEYCODE_FLAG_STD_KEY)
#define    KC_A                        (0x04 | KEYCODE_FLAG_STD_KEY)
#define    KC_B                        (0x05 | KEYCODE_FLAG_STD_KEY)
#define    KC_C                        (0x06 | KEYCODE_FLAG_STD_KEY)
#define    KC_D                        (0x07 | KEYCODE_FLAG_STD_KEY)
#define    KC_E                        (0x08 | KEYCODE_FLAG_STD_KEY)
#define    KC_F                        (0x09 | KEYCODE_FLAG_STD_KEY)
#define    KC_G                        (0x0A | KEYCODE_FLAG_STD_KEY)
#define    KC_H                        (0x0B | KEYCODE_FLAG_STD_KEY)
#define    KC_I                        (0x0C | KEYCODE_FLAG_STD_KEY)
#define    KC_J                        (0x0D | KEYCODE_FLAG_STD_KEY)
#define    KC_K                        (0x0E | KEYCODE_FLAG_STD_KEY)
#define    KC_L                        (0x0F | KEYCODE_FLAG_STD_KEY)
#define    KC_M                        (0x10 | KEYCODE_FLAG_STD_KEY)
#define    KC_N                        (0x11 | KEYCODE_FLAG_STD_KEY)
#define    KC_O                        (0x12 | KEYCODE_FLAG_STD_KEY)
#define    KC_P                        (0x13 | KEYCODE_FLAG_STD_KEY)
#define    KC_Q                        (0x14 | KEYCODE_FLAG_STD_KEY)
#define    KC_R                        (0x15 | KEYCODE_FLAG_STD_KEY)
#define    KC_S                        (0x16 | KEYCODE_FLAG_STD_KEY)
#define    KC_T                        (0x17 | KEYCODE_FLAG_STD_KEY)
#define    KC_U                        (0x18 | KEYCODE_FLAG_STD_KEY)
#define    KC_V                        (0x19 | KEYCODE_FLAG_STD_KEY)
#define    KC_W                        (0x1A | KEYCODE_FLAG_STD_KEY)
#define    KC_X                        (0x1B | KEYCODE_FLAG_STD_KEY)
#define    KC_Y                        (0x1C | KEYCODE_FLAG_STD_KEY)
#define    KC_Z                        (0x1D | KEYCODE_FLAG_STD_KEY)
#define    KC_1                        (0x1E | KEYCODE_FLAG_STD_KEY)
#define    KC_2                        (0x1F | KEYCODE_FLAG_STD_KEY)
#define    KC_3                        (0x20 | KEYCODE_FLAG_STD_KEY)
#define    KC_4                        (0x21 | KEYCODE_FLAG_STD_KEY)
#define    KC_5                        (0x22 | KEYCODE_FLAG_STD_KEY)
#define    KC_6                        (0x23 | KEYCODE_FLAG_STD_KEY)
#define    KC_7                        (0x24 | KEYCODE_FLAG_STD_KEY)
#define    KC_8                        (0x25 | KEYCODE_FLAG_STD_KEY)
#define    KC_9                        (0x26 | KEYCODE_FLAG_STD_KEY)
#define    KC_0                        (0x27 | KEYCODE_FLAG_STD_KEY)

#define    KC_ENTER                    (0x28 | KEYCODE_FLAG_STD_KEY)
#define    KC_ESCAPE                   (0x29 | KEYCODE_FLAG_STD_KEY)
#define    KC_BSPACE                   (0x2A | KEYCODE_FLAG_STD_KEY)
#define    KC_TAB                      (0x2B | KEYCODE_FLAG_STD_KEY)
#define    KC_SPACE                    (0x2C | KEYCODE_FLAG_STD_KEY)
#define    KC_MINUS                    (0x2D | KEYCODE_FLAG_STD_KEY)
#define    KC_EQUAL                    (0x2E | KEYCODE_FLAG_STD_KEY)
#define    KC_LBRACKET                 (0x2F | KEYCODE_FLAG_STD_KEY)
#define    KC_RBRACKET                 (0x30 | KEYCODE_FLAG_STD_KEY)
#define    KC_BSLASH                   (0x31 | KEYCODE_FLAG_STD_KEY)
#define    KC_NONUS_HASH               (0x32 | KEYCODE_FLAG_STD_KEY)
#define    KC_SCOLON                   (0x33 | KEYCODE_FLAG_STD_KEY)
#define    KC_QUOTE                    (0x34 | KEYCODE_FLAG_STD_KEY)
#define    KC_GRAVE                    (0x35 | KEYCODE_FLAG_STD_KEY)
#define    KC_COMMA                    (0x36 | KEYCODE_FLAG_STD_KEY)
#define    KC_DOT                      (0x37 | KEYCODE_FLAG_STD_KEY)
#define    KC_SLASH                    (0x38 | KEYCODE_FLAG_STD_KEY)
#define    KC_CAPSLOCK                 (0x39 | KEYCODE_FLAG_STD_KEY)
#define    KC_F1                       (0x3A | KEYCODE_FLAG_STD_KEY)
#define    KC_F2                       (0x3B | KEYCODE_FLAG_STD_KEY)
#define    KC_F3                       (0x3C | KEYCODE_FLAG_STD_KEY)
#define    KC_F4                       (0x3D | KEYCODE_FLAG_STD_KEY)
#define    KC_F5                       (0x3E | KEYCODE_FLAG_STD_KEY)
#define    KC_F6                       (0x3F | KEYCODE_FLAG_STD_KEY)
#define    KC_F7                       (0x40 | KEYCODE_FLAG_STD_KEY)
#define    KC_F8                       (0x41 | KEYCODE_FLAG_STD_KEY)
#define    KC_F9                       (0x42 | KEYCODE_FLAG_STD_KEY)
#define    KC_F10                      (0x43 | KEYCODE_FLAG_STD_KEY)
#define    KC_F11                      (0x44 | KEYCODE_FLAG_STD_KEY)
#define    KC_F12                      (0x45 | KEYCODE_FLAG_STD_KEY)
#define    KC_PSCREEN                  (0x46 | KEYCODE_FLAG_STD_KEY)
#define    KC_SCROLLLOCK               (0x47 | KEYCODE_FLAG_STD_KEY)
#define    KC_PAUSE                    (0x48 | KEYCODE_FLAG_STD_KEY)
#define    KC_INSERT                   (0x49 | KEYCODE_FLAG_STD_KEY)
#define    KC_HOME                     (0x4A | KEYCODE_FLAG_STD_KEY)
#define    KC_PGUP                     (0x4B | KEYCODE_FLAG_STD_KEY)
#define    KC_DELETE                   (0x4C | KEYCODE_FLAG_STD_KEY)
#define    KC_END                      (0x4D | KEYCODE_FLAG_STD_KEY)
#define    KC_PGDOWN                   (0x4E | KEYCODE_FLAG_STD_KEY)
#define    KC_RIGHT                    (0x4F | KEYCODE_FLAG_STD_KEY)

#define    KC_LEFT                     (0x50 | KEYCODE_FLAG_STD_KEY)
#define    KC_DOWN                     (0x51 | KEYCODE_FLAG_STD_KEY)
#define    KC_UP                       (0x52 | KEYCODE_FLAG_STD_KEY)
#define    KC_NUMLOCK                  (0x53 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_SLASH                 (0x54 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_ASTERISK              (0x55 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_MINUS                 (0x56 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_PLUS                  (0x57 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_ENTER                 (0x58 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_1                     (0x59 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_2                     (0x5A | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_3                     (0x5B | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_4                     (0x5C | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_5                     (0x5D | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_6                     (0x5E | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_7                     (0x5F | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_8                     (0x60 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_9                     (0x61 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_0                     (0x62 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_DOT                   (0x63 | KEYCODE_FLAG_STD_KEY)
#define    KC_KP_COMPOSE               (0x65 | KEYCODE_FLAG_STD_KEY)

#define    KC_LCTRL                    (0xE0 | KEYCODE_FLAG_STD_KEY)
#define    KC_LSHIFT                   (0xE1 | KEYCODE_FLAG_STD_KEY)
#define    KC_LALT                     (0xE2 | KEYCODE_FLAG_STD_KEY)
#define    KC_LGUI                     (0xE3 | KEYCODE_FLAG_STD_KEY)
#define    KC_RCTRL                    (0xE4 | KEYCODE_FLAG_STD_KEY)
#define    KC_RSHIFT                   (0xE5 | KEYCODE_FLAG_STD_KEY)
#define    KC_RALT                     (0xE6 | KEYCODE_FLAG_STD_KEY)
#define    KC_RGUI                     (0xE7 | KEYCODE_FLAG_STD_KEY)

#define    FN_KEY                      (0xEE | KEYCODE_FLAG_STD_KEY)






#define        FN_00                                           (0x0000 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_01                                           (0x0001 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_02                                           (0x0002 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_03                                           (0x0003 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_04                                           (0x0004 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_05                                           (0x0005 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_06                                           (0x0006 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_07                                           (0x0007 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_08                                           (0x0008 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_09                                           (0x0009 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_10                                           (0x000A | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_11                                           (0x000B | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_12                                           (0x000C | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_13                                           (0x000D | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_14                                           (0x000E | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_15                                           (0x000F | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_16                                           (0x0010 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_17                                           (0x0011 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_18                                           (0x0012 | KEYCODE_FLAG_FUNCTION_POINTER)
#define        FN_19                                           (0x0013 | KEYCODE_FLAG_FUNCTION_POINTER)







#define        KC2_UNASSIGNED                                                           (0x0000 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CONSUMER_CONTROL_CA                                                  (0x0001 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_NUMERIC_KEY_PAD_NARY                                                 (0x0002 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PROGRAMMABLE_BUTTONS_NARY                                            (0x0003 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MICROPHONE_CA                                                        (0x0004 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_HEADPHONE_CA                                                         (0x0005 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_GRAPHIC_EQUALIZER_CA                                                 (0x0006 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_10_OSC                                                               (0x0020 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_100_OSC                                                              (0x0021 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AM_PM_OSC                                                            (0x0022 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_POWER_OOC                                                            (0x0030 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_RESET_OSC                                                            (0x0031 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SLEEP_OSC                                                            (0x0032 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SLEEP_AFTER_OSC                                                      (0x0033 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SLEEP_MODE_RTC                                                       (0x0034 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ILLUMINATION_OOC                                                     (0x0035 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FUNCTION_BUTTONS_NARY                                                (0x0036 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_OOC                                                             (0x0040 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_PICK_OSC                                                        (0x0041 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_UP_OSC                                                          (0x0042 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_DOWN_OSC                                                        (0x0043 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_LEFT_OSC                                                        (0x0044 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_RIGHT_OSC                                                       (0x0045 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_ESCAPE_OSC                                                      (0x0046 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_VALUE_INCREASE_OSC                                              (0x0047 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MENU_VALUE_DECREASE_OSC                                              (0x0048 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_DATA_ON_SCREEN_OOC                                                   (0x0060 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CLOSED_CAPTION_OOC                                                   (0x0061 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CLOSED_CAPTION_SELECT_OSC                                            (0x0062 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_VCR_OR_TV_OOC                                                        (0x0063 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BROADCAST_MODE_OSC                                                   (0x0064 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SNAPSHOT_OSC                                                         (0x0065 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_STILL_OSC                                                            (0x0066 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_DISPLAY_BRIGHTNESS_INCREMENT                                         (0x006F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_DISPLAY_BRIGHTNESS_DECREMENT                                         (0x0070 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_KEYBOARD_BRIGHTNESS_INCREMENT                                        (0x0079 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_KEYBOARD_BRIGHTNESS_DECREMENT                                        (0x007A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SELECTION_NARY                                                       (0x0080 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ASSIGN_SELECTION_OSC                                                 (0x0081 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MODE_STEP_OSC                                                        (0x0082 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_RECALL_LAST_OSC                                                      (0x0083 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ENTER_CHANNEL_OSC                                                    (0x0084 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ORDER_MOVIE_OSC                                                      (0x0085 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_LC                                                           (0x0086 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECTION_NARY                                                 (0x0087 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_COMPUTER_SEL                                            (0x0088 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_TV_SEL                                                  (0x0089 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_WWW_SEL                                                 (0x008A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_DVD_SEL                                                 (0x008B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_TELEPHONE_SEL                                           (0x008C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_PROGRAM_GUIDE_SEL                                       (0x008D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_VIDEO_PHONE_SEL                                         (0x008E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_GAMES_SEL                                               (0x008F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_MESSAGES_SEL                                            (0x0090 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_CD_SEL                                                  (0x0091 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_VCR_SEL                                                 (0x0092 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_TUNER_SEL                                               (0x0093 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_QUIT_OSC                                                             (0x0094 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_HELP_OOC                                                             (0x0095 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_TAPE_SEL                                                (0x0096 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_CABLE_SEL                                               (0x0097 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_SATELLITE_SEL                                           (0x0098 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_SECURITY_SEL                                            (0x0099 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_HOME_SEL                                                (0x009A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_CALL_SEL                                                (0x009B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_INCREMENT_OSC                                                (0x009C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_DECREMENT_OSC                                                (0x009D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDIA_SELECT_SAP_SEL                                                 (0x009E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_VCR_PLUS_OSC                                                         (0x00A0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ONCE_OSC                                                             (0x00A1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_DAILY_OSC                                                            (0x00A2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_WEEKLY_OSC                                                           (0x00A3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MONTHLY_OSC                                                          (0x00A4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PLAY_OOC                                                             (0x00B0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PAUSE_OOC                                                            (0x00B1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_RECORD_OOC                                                           (0x00B2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FAST_FORWARD_OOC                                                     (0x00B3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_REWIND_OOC                                                           (0x00B4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SCAN_NEXT_TRACK_OSC                                                  (0x00B5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SCAN_PREVIOUS_TRACK_OSC                                              (0x00B6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_STOP_OSC                                                             (0x00B7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_EJECT_OSC                                                            (0x00B8 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_RANDOM_PLAY_OOC                                                      (0x00B9 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SELECT_DISC_NARY                                                     (0x00BA | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ENTER_DISC_MC                                                        (0x00BB | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_REPEAT_OSC                                                           (0x00BC | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TRACKING_LC                                                          (0x00BD | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TRACK_NORMAL_OSC                                                     (0x00BE | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SLOW_TRACKING_LC                                                     (0x00BF | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FRAME_FORWARD_RTC                                                    (0x00C0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FRAME_BACK_RTC                                                       (0x00C1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MARK_OSC                                                             (0x00C2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CLEAR_MARK_OSC                                                       (0x00C3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_REPEAT_FROM_MARK_OOC                                                 (0x00C4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_RETURN_TO_MARK_OSC                                                   (0x00C5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SEARCH_MARK_FORWARD_OSC                                              (0x00C6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SEARCH_MARK_BACKWARDS_OSC                                            (0x00C7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_COUNTER_RESET_OSC                                                    (0x00C8 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SHOW_COUNTER_OSC                                                     (0x00C9 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TRACKING_INCREMENT_RTC                                               (0x00CA | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TRACKING_DECREMENT_RTC                                               (0x00CB | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_STOP_OR_EJECT_OSC                                                    (0x00CC | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PLAY_OR_PAUSE_OSC                                                    (0x00CD | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PLAY_OR_SKIP_OSC                                                     (0x00CE | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_VOLUME_LC                                                            (0x00E0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BALANCE_LC                                                           (0x00E1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MUTE_OOC                                                             (0x00E2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BASS_LC                                                              (0x00E3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TREBLE_LC                                                            (0x00E4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BASS_BOOST_OOC                                                       (0x00E5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SURROUND_MODE_OSC                                                    (0x00E6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_LOUDNESS_OOC                                                         (0x00E7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MPX_OOC                                                              (0x00E8 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_VOLUME_INCREMENT_RTC                                                 (0x00E9 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_VOLUME_DECREMENT_RTC                                                 (0x00EA | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SPEED_SELECT_OSC                                                     (0x00F0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PLAYBACK_SPEED_NARY                                                  (0x00F1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_STANDARD_PLAY_SEL                                                    (0x00F2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_LONG_PLAY_SEL                                                        (0x00F3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_EXTENDED_PLAY_SEL                                                    (0x00F4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SLOW_OSC                                                             (0x00F5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FAN_ENABLE_OOC                                                       (0x0100 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FAN_SPEED_LC                                                         (0x0101 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_LIGHT_ENABLE_OOC                                                     (0x0102 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_LIGHT_ILLUMINATION_LEVEL_LC                                          (0x0103 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CLIMATE_CONTROL_ENABLE_OOC                                           (0x0104 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ROOM_TEMPERATURE_LC                                                  (0x0105 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SECURITY_ENABLE_OOC                                                  (0x0106 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_FIRE_ALARM_OSC                                                       (0x0107 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_POLICE_ALARM_OSC                                                     (0x0108 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_PROXIMITY_LC                                                         (0x0109 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MOTION_OSC                                                           (0x010A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_DURESS_ALARM_OSC                                                     (0x010B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_HOLDUP_ALARM_OSC                                                     (0x010C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_MEDICAL_ALARM_OSC                                                    (0x010D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BALANCE_RIGHT_RTC                                                    (0x0150 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BALANCE_LEFT_RTC                                                     (0x0151 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BASS_INCREMENT_RTC                                                   (0x0152 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_BASS_DECREMENT_RTC                                                   (0x0153 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TREBLE_INCREMENT_RTC                                                 (0x0154 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_TREBLE_DECREMENT_RTC                                                 (0x0155 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SPEAKER_SYSTEM_CL                                                    (0x0160 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_LEFT_CL                                                      (0x0161 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_RIGHT_CL                                                     (0x0162 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_CENTER_CL                                                    (0x0163 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_FRONT_CL                                                     (0x0164 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_CENTER_FRONT_CL                                              (0x0165 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_SIDE_CL                                                      (0x0166 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_SURROUND_CL                                                  (0x0167 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_LOW_FREQUENCY                                                (0x0168 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_TOP_CL                                                       (0x0169 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_CHANNEL_UNKNOWN_CL                                                   (0x016A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SUB_CHANNEL_LC                                                       (0x0170 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SUB_CHANNEL_INCREMENT_OSC                                            (0x0171 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_SUB_CHANNEL_DECREMENT_OSC                                            (0x0172 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ALTERNATE_AUDIO_INCREMENT_OSC                                        (0x0173 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_ALTERNATE_AUDIO_DECREMENT_OSC                                        (0x0174 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_APPLICATION_LAUNCH_BUTTONS_NARY                                      (0x0180 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LAUNCH_BUTTON_CONFIGURATION                                       (0x0181 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_PROGRAMMABLE_BUTTON                                               (0x0182 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CONSUMER_CONTROL                                                  (0x0183 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_WORD_PROCESSOR_SEL                                                (0x0184 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_TEXT_EDITOR_SEL                                                   (0x0185 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_SPREADSHEET_SEL                                                   (0x0186 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_GRAPHICS_EDITOR_SEL                                               (0x0187 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_PRESENTATION_APP_SEL                                              (0x0188 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DATABASE_APP_SEL                                                  (0x0189 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_EMAIL_READER_SEL                                                  (0x018A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_NEWSREADER_SEL                                                    (0x018B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_VOICEMAIL_SEL                                                     (0x018C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CONTACTS_OR_ADDRESS_BOOK_SEL                                      (0x018D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CALENDAR_OR_SCHEDULE_SEL                                          (0x018E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_TASK_OR_PROJECT_MANAGER_SEL                                       (0x018F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LOG_OR_JOURNAL_OR_TIMECARD_SEL                                    (0x0190 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CHECKBOOK_OR_FINANCE_SEL                                          (0x0191 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CALCULATOR_SEL                                                    (0x0192 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_AV_CAPTURE_OR_PLAYBACK_SEL                                        (0x0193 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LOCAL_MACHINE_BROWSER_SEL                                         (0x0194 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LAN_OR_WAN_BROWSER_SEL                                            (0x0195 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_INTERNET_BROWSER_SEL                                              (0x0196 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_REMOTE_NETWORKING_OR_ISP                                          (0x0197 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_NETWORK_CONFERENCE_SEL                                            (0x0198 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_NETWORK_CHAT_SEL                                                  (0x0199 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_TELEPHONY_OR_DIALER_SEL                                           (0x019A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LOGON_SEL                                                         (0x019B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LOGOFF_SEL                                                        (0x019C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_LOGON_OR_LOGOFF_SEL                                               (0x019D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_TERMINAL_LOCK_OR_SCREENSAVER_SEL                                  (0x019E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CONTROL_PANEL_SEL                                                 (0x019F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_COMMAND_LINE_PROCESSOR_OR_RUN_SEL                                 (0x01A0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_PROCESS_OR_TASK_MANAGER_SEL                                       (0x01A1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_SELECT_TASK_OR_APPLICATION_SEL                                    (0x01A2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_NEXT_TASK_OR_APPLICATION_SEL                                      (0x01A3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_PREVIOUS_TASK_OR_APPLICATION_SEL                                  (0x01A4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_PREEMPTIVE_HALT                                                   (0x01A5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_INTEGRATED_HELP_CENTER_SEL                                        (0x01A6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DOCUMENTS_SEL                                                     (0x01A7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_THESAURUS_SEL                                                     (0x01A8 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DICTIONARY_SEL                                                    (0x01A9 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DESKTOP_SEL                                                       (0x01AA | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_SPELL_CHECK_SEL                                                   (0x01AB | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_GRAMMAR_CHECK_SEL                                                 (0x01AC | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_WIRELESS_STATUS_SEL                                               (0x01AD | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_KEYBOARD_LAYOUT_SEL                                               (0x01AE | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_VIRUS_PROTECTION_SEL                                              (0x01AF | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ENCRYPTION_SEL                                                    (0x01B0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_SCREEN_SAVER_SEL                                                  (0x01B1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ALARMS_SEL                                                        (0x01B2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CLOCK_SEL                                                         (0x01B3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_FILE_BROWSER_SEL                                                  (0x01B4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_POWER_STATUS_SEL                                                  (0x01B5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_IMAGE_BROWSER_SEL                                                 (0x01B6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_AUDIO_BROWSER_SEL                                                 (0x01B7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_MOVIE_BROWSER_SEL                                                 (0x01B8 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DIGITAL_RIGHTS_MANAGER_SEL                                        (0x01B9 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_DIGITAL_WALLET_SEL                                                (0x01BA | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_INSTANT_MESSAGING_SEL                                             (0x01BC | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_OEM_FEATURES_OR__TIPS_OR_TUTORIAL                                 (0x01BD | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_OEM_HELP_SEL                                                      (0x01BE | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ONLINE_COMMUNITY_SEL                                              (0x01BF | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ENTERTAINMENT_CONTENT                                             (0x01C0 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ONLINE_SHOPPING_BROWSER_SEL                                       (0x01C1 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_SMARTCARD_INFORMATION_OR_HELP_SEL                                 (0x01C2 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_MARKET_MONITOR_OR_FINANCE                                         (0x01C3 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_CUSTOMIZED_CORPORATE_NEWS                                         (0x01C4 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_ONLINE_ACTIVITY_BROWSER_SEL                                       (0x01C5 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_RESEARCH_OR_SEARCH_BROWSER_SEL                                    (0x01C6 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AL_AUDIO_PLAYER_SEL                                                  (0x01C7 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_GENERIC_GUI_APPLICATION                                              (0x0200 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NEW_SEL                                                           (0x0201 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_OPEN_SEL                                                          (0x0202 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_CLOSE_SEL                                                         (0x0203 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_EXIT_SEL                                                          (0x0204 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_MAXIMIZE_SEL                                                      (0x0205 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_MINIMIZE_SEL                                                      (0x0206 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SAVE_SEL                                                          (0x0207 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PRINT_SEL                                                         (0x0208 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PROPERTIES_SEL                                                    (0x0209 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_UNDO_SEL                                                          (0x021A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_COPY_SEL                                                          (0x021B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_CUT_SEL                                                           (0x021C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PASTE_SEL                                                         (0x021D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_ALL_SEL                                                    (0x021E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FIND_SEL                                                          (0x021F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FIND_AND_REPLACE_SEL                                              (0x0220 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SEARCH_SEL                                                        (0x0221 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_GO_TO_SEL                                                         (0x0222 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_HOME_SEL                                                          (0x0223 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_BACK_SEL                                                          (0x0224 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FORWARD_SEL                                                       (0x0225 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_STOP_SEL                                                          (0x0226 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_REFRESH_SEL                                                       (0x0227 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PREVIOUS_LINK_SEL                                                 (0x0228 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NEXT_LINK_SEL                                                     (0x0229 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_BOOKMARKS_SEL                                                     (0x022A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_HISTORY_SEL                                                       (0x022B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SUBSCRIPTIONS_SEL                                                 (0x022C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ZOOM_IN_SEL                                                       (0x022D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ZOOM_OUT_SEL                                                      (0x022E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ZOOM_LC                                                           (0x022F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FULL_SCREEN_VIEW_SEL                                              (0x0230 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NORMAL_VIEW_SEL                                                   (0x0231 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_VIEW_TOGGLE_SEL                                                   (0x0232 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SCROLL_UP_SEL                                                     (0x0233 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SCROLL_DOWN_SEL                                                   (0x0234 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SCROLL_LC                                                         (0x0235 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PAN_LEFT_SEL                                                      (0x0236 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PAN_RIGHT_SEL                                                     (0x0237 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PAN_LC                                                            (0x0238 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NEW_WINDOW_SEL                                                    (0x0239 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_TILE_HORIZONTALLY_SEL                                             (0x023A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_TILE_VERTICALLY_SEL                                               (0x023B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FORMAT_SEL                                                        (0x023C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_EDIT_SEL                                                          (0x023D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_BOLD_SEL                                                          (0x023E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ITALICS_SEL                                                       (0x023F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_UNDERLINE_SEL                                                     (0x0240 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_STRIKETHROUGH_SEL                                                 (0x0241 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SUBSCRIPT_SEL                                                     (0x0242 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SUPERSCRIPT_SEL                                                   (0x0243 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ALL_CAPS_SEL                                                      (0x0244 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ROTATE_SEL                                                        (0x0245 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_RESIZE_SEL                                                        (0x0246 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FLIP_HORIZONTAL_SEL                                               (0x0247 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FLIP_VERTICAL_SEL                                                 (0x0248 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_MIRROR_HORIZONTAL_SEL                                             (0x0249 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_MIRROR_VERTICAL_SEL                                               (0x024A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FONT_SELECT_SEL                                                   (0x024B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FONT_COLOR_SEL                                                    (0x024C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FONT_SIZE_SEL                                                     (0x024D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_LEFT_SEL                                                  (0x024E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_CENTER_H_SEL                                              (0x024F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_RIGHT_SEL                                                 (0x0250 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_BLOCK_H_SEL                                               (0x0251 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_TOP_SEL                                                   (0x0252 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_CENTER_V_SEL                                              (0x0253 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_BOTTOM_SEL                                                (0x0254 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_JUSTIFY_BLOCK_V_SEL                                               (0x0255 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INDENT_DECREASE_SEL                                               (0x0256 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INDENT_INCREASE_SEL                                               (0x0257 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NUMBERED_LIST_SEL                                                 (0x0258 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_RESTART_NUMBERING_SEL                                             (0x0259 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_BULLETED_LIST_SEL                                                 (0x025A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PROMOTE_SEL                                                       (0x025B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DEMOTE_SEL                                                        (0x025C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_YES_SEL                                                           (0x025D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_NO_SEL                                                            (0x025E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_CANCEL_SEL                                                        (0x025F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_CATALOG_SEL                                                       (0x0260 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_BUY_OR_CHECKOUT_SEL                                               (0x0261 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ADD_TO_CART_SEL                                                   (0x0262 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_EXPAND_SEL                                                        (0x0263 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_EXPAND_ALL_SEL                                                    (0x0264 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_COLLAPSE_SEL                                                      (0x0265 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_COLLAPSE_ALL_SEL                                                  (0x0266 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PRINT_PREVIEW_SEL                                                 (0x0267 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PASTE_SPECIAL_SEL                                                 (0x0268 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_MODE_SEL                                                   (0x0269 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DELETE_SEL                                                        (0x026A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_LOCK_SEL                                                          (0x026B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_UNLOCK_SEL                                                        (0x026C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_PROTECT_SEL                                                       (0x026D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_UNPROTECT_SEL                                                     (0x026E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ATTACH_COMMENT_SEL                                                (0x026F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DELETE_COMMENT_SEL                                                (0x0270 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_VIEW_COMMENT_SEL                                                  (0x0271 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_WORD_SEL                                                   (0x0272 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_SENTENCE_SEL                                               (0x0273 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_PARAGRAPH_SEL                                              (0x0274 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_COLUMN_SEL                                                 (0x0275 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_ROW_SEL                                                    (0x0276 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_TABLE_SEL                                                  (0x0277 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_OBJECT_SEL                                                 (0x0278 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_REDO_OR_REPEAT_SEL                                                (0x0279 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SORT_SEL                                                          (0x027A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SORT_ASCENDING_SEL                                                (0x027B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SORT_DESCENDING_SEL                                               (0x027C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FILTER_SEL                                                        (0x027D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SET_CLOCK_SEL                                                     (0x027E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_VIEW_CLOCK_SEL                                                    (0x027F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SELECT_TIME_ZONE_SEL                                              (0x0280 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_EDIT_TIME_ZONES_SEL                                               (0x0281 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SET_ALARM_SEL                                                     (0x0282 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_CLEAR_ALARM_SEL                                                   (0x0283 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SNOOZE_ALARM_SEL                                                  (0x0284 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_RESET_ALARM_SEL                                                   (0x0285 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SYNCHRONIZE_SEL                                                   (0x0286 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SEND_OR_RECEIVE_SEL                                               (0x0287 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SEND_TO_SEL                                                       (0x0288 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_REPLY_SEL                                                         (0x0289 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_REPLY_ALL_SEL                                                     (0x028A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_FORWARD_MSG_SEL                                                   (0x028B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SEND_SEL                                                          (0x028C | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_ATTACH_FILE_SEL                                                   (0x028D | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_UPLOAD_SEL                                                        (0x028E | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DOWNLOAD_SEL                                                      (0x028F | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SET_BORDERS_SEL                                                   (0x0290 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_ROW_SEL                                                    (0x0291 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_COLUMN_SEL                                                 (0x0292 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_FILE_SEL                                                   (0x0293 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_PICTURE_SEL                                                (0x0294 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_OBJECT_SEL                                                 (0x0295 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_INSERT_SYMBOL_SEL                                                 (0x0296 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SAVE_AND_CLOSE_SEL                                                (0x0297 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_RENAME_SEL                                                        (0x0298 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_MERGE_SEL                                                         (0x0299 | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_SPLIT_SEL                                                         (0x029A | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DISRIBUTE_HORIZONTALLY_SEL                                        (0x029B | KEYCODE_FLAG_CONSUMER_KEY)
#define        KC2_AC_DISTRIBUTE_VERTICALLY_SEL                                         (0x029C | KEYCODE_FLAG_CONSUMER_KEY)


#endif // __APP_KEY_MATRIX_DECLARATION__HH_
