/* Copyright Statement:
 *
 * (C) 2024  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AIROHA SOFTWARE")
 * RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES ARE PROVIDED
 * TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __APP_PINMUX_CONFIG_PARSER_H__
#define __APP_PINMUX_CONFIG_PARSER_H__



#include "application.h"

typedef enum
{
    APP_PINMUX_FUNC_GPIO_OUTPUT = 0,
    APP_PINMUX_FUNC_MUTI_FUN_1,
    APP_PINMUX_FUNC_MUTI_FUN_2,
    APP_PINMUX_FUNC_MUTI_FUN_3,
    APP_PINMUX_FUNC_MUTI_FUN_4,
    APP_PINMUX_FUNC_MUTI_FUN_5,
    APP_PINMUX_FUNC_MUTI_FUN_6,
    APP_PINMUX_FUNC_MUTI_FUN_7,
    APP_PINMUX_FUNC_PWM,            //8
    APP_PINMUX_FUNC_KEY_MATRIX,     //9
    APP_PINMUX_FUNC_MUTI_FUN_10,
    APP_PINMUX_FUNC_MUTI_FUN_11,
    APP_PINMUX_FUNC_EINT = 12,
    APP_PINMUX_FUNC_HW_DEBUG,
    APP_PINMUX_FUNC_MUTI_FUN_14,
    APP_PINMUX_FUNC_MUTI_FUN_15,
    APP_PINMUX_FUNC_MUTI_FUN_16,
}T_APP_PINMUX_FUN_E;


typedef enum
{
    APP_PINMUX_USAGE_OUTPUT_NONE,
    APP_PINMUX_USAGE_OUTPUT_LED_SINGLE_0,
    APP_PINMUX_USAGE_OUTPUT_LED_SINGLE_1,
    APP_PINMUX_USAGE_OUTPUT_LED_SINGLE_2,
    APP_PINMUX_USAGE_OUTPUT_LED_RGB_0,
    APP_PINMUX_USAGE_OUTPUT_LED_RGB_1,
    APP_PINMUX_USAGE_OUTPUT_LED_RGB_2,

    APP_PINMUX_USAGE_OUTPUT_IR_PD_CTRL = 0x80,
    APP_PINMUX_USAGE_OUTPUT_SCROLL_EN_CTRL,
    APP_PINMUX_USAGE_OUTPUT_FUEL_GUAGE_CTRL,
    APP_PINMUX_USAGE_OUTPUT_SENSOR_NRESET_CTRL,
    APP_PINMUX_USAGE_OUTPUT_CHARGE_ENA_CTRL,
    APP_PINMUX_USAGE_OUTPUT_LED_POWER_CTRL,
    APP_PINMUX_USAGE_OUTPUT_IR_PD_CTRL_2,

    APP_PINMUX_USAGE_OUTPUT_DEBUG_SPI_CB_SIGNAL = 0xC0,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_LATCH_REPORT_SIGNAL,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_TX_NACK,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DEBUG_1,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DEBUG_2,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DEBUG_3,

    APP_PINMUX_USAGE_OUTPUT_DEBUG_DONGLE_BT_CB_SIGNAL = 0xD0,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DONGLE_SW_ISR_SIGNAL,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DONGLE_SEQ_ERR_SIGNAL,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DONGLE_SEQ_ERR_GAP_SIGNAL,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_DONGLE_DUPLICATE_SIGNAL,

    APP_PINMUX_USAGE_OUTPUT_DEBUG_USB_TX_SIGNAL = 0xD8,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_USB_TX_DONE_SIGNAL,
    APP_PINMUX_USAGE_OUTPUT_DEBUG_USB_SOF_SIGNAL,

}T_APP_PINMUX_USAGE_OUTPUT_E;


typedef enum
{
    APP_PINMUX_USAGE_EINT_NONE,
    #if defined(CONFIG_AIR_PRODUCT_TYPE_MOUSE)
    APP_PINMUX_USAGE_EINT_MOUSE_L_KEY,
    APP_PINMUX_USAGE_EINT_MOUSE_R_KEY,
    APP_PINMUX_USAGE_EINT_MOUSE_M_KEY,
    APP_PINMUX_USAGE_EINT_MOUSE_FW_KEY,
    APP_PINMUX_USAGE_EINT_MOUSE_BW_KEY,
    APP_PINMUX_USAGE_EINT_MOUSE_DPI_KEY, //6
    APP_PINMUX_USAGE_EINT_MOUSE_REPORT_RATE_CHANGE_KEY, //7
    APP_PINMUX_USAGE_EINT_MOUSE_MOTION_PIN, //8
    APP_PINMUX_USAGE_EINT_MOUSE_BT_MODE_KEY, //9
    APP_PINMUX_USAGE_EINT_MOUSE_2_4G_MODE_KEY, //10
    #endif
}T_APP_PINMUX_USAGE_EINT_E;


typedef struct
{
    uint8_t fun_type;
    uint8_t usage;
    uint8_t parameter;
}__packed T_GPIO_CONFIG_S;

typedef struct
{
    uint16_t ver;
    uint8_t enable;
    T_GPIO_CONFIG_S gpio[48];
}__packed T_DYNAMIC_PINMUX_CONFIG_S;



void app_pin_config_parser_init(T_GPIO_PIN_USAGE_LIST_S * usage_list);


#endif //__APP_PINMUX_CONFIG_PARSER_H__

