# Copyright Statement:
#
# (C) 2024  Airoha Technology Corp. All rights reserved.
#
# This software/firmware and related documentation ("Airoha Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
# Without the prior written permission of Airoha and/or its licensors,
# any reproduction, modification, use or disclosure of Airoha Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.
# You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
# if you have agreed to and been bound by the applicable license agreement with
# Airoha ("License Agreement") and been granted explicit permission to do so within
# the License Agreement ("Permitted User").  If you are not a Permitted User,
# please cease any access or use of Airoha Software immediately.
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
# ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
# WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
# AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
#


##############################################
#           Custom feature option            #
##############################################
# default
## part1: configure y/n
AIR_PKA_SHARE_ENABLE=y
AIR_HID_COMMON_SERVICE=y
AIR_HID_COMMON_MEMORY=y
AIR_PRODUCT_TYPE_MOUSE=y
AIR_HID_EXPRESS_SERVICE=y

AIR_BASIC_LA_DEBUG=n
AIR_REPORT_DATA_LOG=n
AIR_REPORT_LOG_NACK_BIT=n
AIR_DEBUG_POLLING_LOG=y
AIR_DISABLE_IRQ_LOG_ENABLE=y
AIR_FAKE_REPORT=y

AIR_HID_DEVICE_SCENARIO_SERVICE_KEY_REMAP=y
AIR_FN_KEY_ENABLE=n
AIR_KEY_REMAP_FRONTEND_RISCV=y
AIR_KEY_REMAP_BACKEND_RISCV=y
AIR_WHEEL_REMAP=y
AIR_USB_CCNI_WAKEUP_CM33=y

AIR_KEY_SW_DEBOUNCE=n
AIR_WHEEL_IR_COMPARATOR=n

AIR_BT_DATA_MERGE_XY=y
AIR_NVIDIA_REFLEX=n
AIR_IRPT_PIN_CTRL=n

AIR_ONLINE_SWLA_ENABLE=n
AIR_HID_BT_MODE=y
AIR_2_4G_RELIABLE_RETRASMISSION=y
AIR_SLEEP_MANAGER_LIGHT_MODE_ENABLE=y
## part2: need to set specified value

AIR_BYPASS_SYSLOG_WITH_LOG_FLOW_ENABLE=y
